$ANSIBLE_VAULT;1.1;AES256
35356637323764363732303830393065303039333336316664336364326566643865633665613939
3765613066623038313836656434396237306332643739610a386436353235643936366662306636
63316131313439356663343663306131306531373330326239633261366236343437363166626336
3336616237616162300a393136616232616433653935633563626432333361366137633966366237
34643730616137636634383131386235636535663833306639356339393231613565386432323634
31393564313635636531333664383238323234666232643035386234386539646663316661313631
34663161396436386566363033343938613431656539656534653066663336613463313639383865
32626139343063393263376162663266373235383134326531613664303932633739356265623932
65303239643266653362303138653666376131363737386630313563613938616130313538633434
38636533373438646461643065343864656233646634343432653263363032363930636362323938
62663731333336376662363531316661306534643239346363656337393237653964303563623634
36653232633031386166653339366463346234376435396166656663353962656162616237373630
63313336356639393231336462383031343938356265656563323233333131626436636562623237
34353065396566313666643430386230353330366137363238383735343234343066633763356133
643536636633373865616137383833343133
