$ANSIBLE_VAULT;1.1;AES256
39343134353937376139326361343130633634306264306563343162643638393463623464353362
3134373262303738326463373733396461333631333265660a653938653732623739383833633066
33313838313432633838383737366133313031316331663862323534343462656566303534373066
6631323865303462360a346264616233633862613036363438666335373362646532343732623063
33386636313238393762636564333334623166653135623866383932303730313237353731346534
37656435363937323431636165666632653235613631616262623132313534646162376465303434
65636365303634333162333631373865373839303134373533373866386332323862366337656336
38373030333065663437353030313731393966373261353063356631623331646332613863623934
33316333623738303164626537303836653838343163623539396465666135353932353639396564
63336230363865613538363231393966666663633631336563646661373762633735613462306139
64366433346533326164333938313435396335306232633265313434373635613765623939363962
30386363363865306562663535353035613165623932323262356537303863336261323766303938
39383537663063343565663737396134366530626638363963323532666463613531663330613037
3966333034386564376261366561306138353962386161396363
