argument_specs:
  main:
    short_description: Deploys Docker based GitHub Runners
    author:
      - Markus Heck
    options:
      docker_github_runner_base_path:
        type: str
        required: false
        default: /opt/docker-apps
        description: Base path where docker compose project folder will be located on the target system
      docker_github_runner_state:
        type: str
        required: false
        default: present
        choices:
          - present
          - absent
        description: State of the docker compose project
      docker_github_runner_github_runner_token:
        type: str
        required: true
        description: GitHub Runner token to register the runner with GitHub
      docker_github_runner_update_containers:
        type: bool
        required: false
        default: false
        description: Update all containers of the docker compose project to the latest image versions. This will restart the containers.