ansible_user: "ansible"
ansible_become_pass: "{{ vault_user_password_ansible }}"

user_ssh_pubkey_ansible: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIR0jjya7pYiGrEu8PwD7UjlmVHA1doC8mM0yg/BZwMp markus@DESKTOP-1DT3KOR"

system_users:
    - username: "markus"
      password_hash: "{{ vault_user_password_hash_markus }}"
      groups: sudo
      update_password: false
      ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJFyi+PrxL/KcW/jQK70vBcWhilmYERGaeWFxOg9RiVq markus 2024-08-09"
      ssh_pubkey_replace: false


system_packages:
  - htop
  - btop
  - sudo
  - nano
  - screen
  - zstd
  - iftop
  - tree

