ansible_user: "ansible"
ansible_become_pass: "{{ vault_user_password_ansible }}"
# ansible_ssh_private_key_file: "files/id_ed25519_ansible"

user_ssh_pubkey_ansible: "{{ lookup('file', '../files/ssh_keys/id_ed25519_ansible.pub') }}"

system_users:
    - username: "markus"
      password_hash: "{{ vault_user_password_hash_markus }}"
      groups: sudo
      update_password: false
      ssh_pubkey: "{{ lookup('file', '../files/ssh_keys/id_ed25519_markus.pub') }}"


system_packages:
  - htop
  - sudo
  - nano
  - screen
  - zstd
  - iftop
  - tree

