$ANSIBLE_VAULT;1.1;AES256
30303231336439303964306234313766653932346333623362353366663434393162316131663535
3337366630386437316137303836353333363661376561370a336432633736656466373563383635
36626634663535383930316635393863626432636165323063333262623439373834616235353331
6333623561336165380a306430303330623066306662343334366366333135613637666132316334
66353363643138633137363063346638313165376361303366613834636532633333383663373566
35373935666332336533306561353430363664383537343134626466363238653732333635613938
39626563666465656232386432353332363664336638636165656365356532333065336165636264
65373738313334353734633430313164653964313063636135313036666562663564326264353763
33656531623433343263396438643937313266323436336530336439396566336562346338633066
34646232636435346336326236306661383336303436373264393632643534336336363163376633
66383663346138326564633533376136376661356638393036653437633934646638633935313466
65326432633661313235613365663234636537326564616361633563303561313063623733613562
31613934343262353636633330356135633166666134613762326538613237666438383263356636
38323066666661646562396662373739323264643266383933656531356531373238613838613865
39366435346632613038633834633139636636656564393238333037666161666161383536383236
64303434636331383438316636313433646366396666653239623863396232376163303165363134
62383430656264373237306261636662326263363165336430663861356666366566373533656239
35613863343936333262346465623563306565353336633966376338393961363663303533313434
37353139396361323331656239663036353061383238336234396638366331643939316337343561
63633335376661623330656164653536626234376137616438386132343833636562616664666230
3933
