ansible_user: "ansible"
ansible_ssh_private_key_file: "files/id_ed25519_ansible"

user_ssh_pubkey_markus: "{{ lookup('file', '../files/id_ed25519_markus.pub') }}"
user_ssh_pubkey_ansible: "{{ lookup('file', '../files/id_ed25519_ansible.pub') }}"