$ANSIBLE_VAULT;1.1;AES256
31643364393734393433313761316333313932353636303832393438656465633561303363326631
3235373865383435303361663566633231323430313866360a346137383438303439356637326334
38346535386665633032373533666231653533363266386430616333323933333464343664306137
3361626565366464300a333965326437363866356634316139636366383636643266383632373339
66346661316533333730656266393035626137643633626361623935343438636463313663636630
65656134373339333166333564393864646431383833393066386462646132646531646334633662
66633136643034616665353266363865393861383439303335323636663132366438666530313362
64353636616431626334336464383561663439346230623461306532323965666634373538363138
64663639626437383436663666313166376266383666653331363131336632633635
