services:
  db:
    image: mariadb:11.4
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=${_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:31.0.12-fpm
    restart: unless-stopped
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    networks:
      - traefik_gateway
      - internal
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=${_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  cron:
    image: nextcloud:31.0.12-fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    networks:
      - internal
    entrypoint: /cron.sh
    depends_on:
      - db
      - app

  web:
    ports:
      - 8084:80
    image: nginx
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.projekt-adler.eu`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.davredirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.davredirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.davredirect.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nextcloudsts.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.nextcloudsts.headers.stspreload=true"
      - "traefik.http.middlewares.nextcloudsts.headers.stsseconds=31536000"
      - "traefik.http.middlewares.nextcloudsts.headers.isdevelopment=false"
      - "traefik.http.middlewares.nextcloudsts.headers.customResponseHeaders.X-Robots-Tag=noindex, nofollow"
      - "traefik.http.routers.nextcloud.middlewares=davredirect,nextcloudsts"

    links:
      - app
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./php.ini:/etc/nginx/conf.d/php.ini:ro
    networks:
      traefik_gateway:
      internal:
        ipv4_address: 172.32.2.100
    volumes_from:
      - app

  collabora:
    image: collabora/code
    cap_add:
      - MKNOD
    expose:
      - 9980
    depends_on:
      - web
    networks:
      traefik_gateway:
        ipv4_address: 172.16.2.90
      internal:
    environment:
      - domain=cloud.projekt-adler.eu
      - username=administrator
      - password=BGoaNIVJyvkXl7Y
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.rule=(Host(`collabora.projekt-adler.eu`))"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.routers.collabora.tls.certresolver=le"
      - "traefik.http.routers.collabora.service=collabora"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"

volumes:
  nextcloud:
  db:

networks:
  traefik_gateway:
    name: traefik_gateway
    external: true
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.32.2.0/24
          gateway: 172.32.2.1
