name: github-runner  # default if not overwritten with COMPOSE_PROJECT_NAME env variable
services:
  dind:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 10
    restart: unless-stopped

  worker:
    image: myoung34/github-runner:ubuntu-noble
    profiles: [ managed-by-watchdog ]  # this avoids automatic start with docker compose up
    depends_on:
      dind:
        condition: service_healthy
    restart: no  # doing with watchdog as restart does not do a clean restart
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      EPHEMERAL: 1
      ORG_NAME: ProjektAdLer
      RUNNER_NAME: debian-adler-docker-${COMPOSE_PROJECT_NAME}
      RUNNER_TOKEN: ${RUNNER_TOKEN:-"some pointless dummy text to avoid docker compose warnings"} # set through watchdog
      RUNNER_SCOPE: 'org'
      LABELS: linux,x64,ubuntu-24.04,self-hosted
      DOCKER_HOST: tcp://dind:2375
      DOCKER_TLS_CERTDIR: ""

  watchdog:
    image: docker:cli
    depends_on:
      - dind
    restart: unless-stopped
    environment:
      GH_PAT: ${GITHUB_ACCESS_TOKEN}
      ORG_NAME: ProjektAdLer
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    command: |
      sh -c "trap 'docker compose stop worker; exit 0' TERM INT  # this will stop the worker when the watchdog is stopped, making the worker to also stop when running docker compose down
      cd /workdir
      apk add --no-cache curl jq
      while true; do
        if [ -z \"\$(docker compose ps worker -aq --status running)\" ]; then
          # Stop and remove the runner and DinD containers
          docker compose stop worker dind
          docker compose rm -f worker dind
      
          # Start DinD container first
          docker compose up -d dind
      
          # Wait for DinD to be healthy
          echo 'Waiting for DinD to be ready...'
          until docker compose ps dind | grep '(healthy)'; do
            sleep 2
          done

          # Start the runner
          REGISTRATION_TOKEN=$(curl -sX POST -H \"Authorization: token $$GH_PAT\" \"https://api.github.com/orgs/$$ORG_NAME/actions/runners/registration-token\" | jq -r '.token')
          RUNNER_TOKEN=$$REGISTRATION_TOKEN docker compose up -d --force-recreate worker
        fi
        sleep 5
      done"
    volumes:
      - .:/workdir  # needed to be able to use docker compose in container
      - /var/run/docker.sock:/var/run/docker.sock  # Needed for controlling Docker
