backup_encryption_password: "changeme"  # Restic repository password

# repository (rest server)
backup_repository_rest_url: "rest:http://host/myrepo"  # Restic repository URL (REST)
backup_repository_rest_username: ""  # Restic repository username (REST)
backup_repository_rest_password: ""  # Restic repository password (REST)
backup_repository_rest_ca_file_content: ""  # CA file content for TLS connections

# configure data to back up
backup_paths: ["/"]  # List of paths to back up
backup_exclude: |  # Patterns to exclude from backup
  /proc
  /sys
  /dev
  /run
  /tmp
  /var/tmp
  /var/cache
  /var/run
backup_iexclude: ""  # Patterns to case-insensitively exclude

# schedule
backup_schedule: "0 6 * * *"  # Cron schedule (default: daily at 6am)

# typically there is no reason to change these settings
backup_system_user: restic  # System user to run the backup as. Will be created if it does not exist as a system user with `sudo /usr/bin/restic backup` permissions
backup_config_directory: /etc/restic  # Directory for restic config and scripts


