services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    networks:
      default:
      traefik_gateway:
        ipv4_address: 172.16.2.100
    ports:
      - "80:80"
      - "443:443"
      - "24550:24550"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - acme:/acme

volumes:
  acme:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.45.0.0/24"
  traefik_gateway:
    name: traefik_gateway
    external: true
