providers:
  docker:
    exposedByDefault: false
    network: traefik_gateway

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    transport:
      respondingTimeouts:
        writeTimeout: 0s
        readTimeout: 0s
    address: :443
  ea_postgres:
    address: :24550/tcp

certificatesresolvers:
  le:
    acme:
      email: markus.heck@hs-kempten.de
      storage: /acme/acme.json
      tlschallenge: true
accessLog:
  filePath: "/accesslogs/access.log"

log:
  level: WARN
#api:
#  dashboard: true
#  insecure: true


http:
  middlewares:
    add-robots-headers:
      headers:
        X-Robots-Tag: „noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex“
  middlewaresChain:
    default:
      middlewares:
        - add-robots-headers
