---

- name: Install docker package
  when: docker_apps_install_docker
  ansible.builtin.package:
    name: docker.io
    state: present
    cache_valid_time: 3600

- name: Ensure docker_apps_base_path exists
  file:
    path: "{{ docker_apps_base_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy docker compose projects
  include_tasks: "{{ role_path }}/tasks/deploy_app.yml"
  loop: "{{ docker_apps_projects }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    docker_apps_project: "{{ item }}"